language: php

sudo: required

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - composer dump-autoload

script: vendor/bin/phpunit

branches:
  only:
    - master