language: php

sudo: required

group: deprecated-2017Q4

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - composer dump-autoload

script: vendor/bin/phpunit

branches:
  only:
    - master